##############################################################################
# Form implementation generated from reading ui file 'phonebook_tempalte.ui' #
#                                                                            #
# Created by: PyQt5 UI code generator 5.15.10                                #
#                                                                            #
# WARNING: Any manual changes made to this file will be lost when pyuic5 is  #
# run again. Do not edit this file unless you know what you are doing.       #
##############################################################################


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
import os



class Ui_Dialog(object):    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 470)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(522, 470))
        Dialog.setMaximumSize(QtCore.QSize(522, 470))
        Dialog.setBaseSize(QtCore.QSize(0, 0))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/avatardefault_92824.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.contacts_label = QtWidgets.QLabel(Dialog)
        self.contacts_label.setGeometry(QtCore.QRect(130, 20, 58, 16))
        self.contacts_label.setObjectName("contacts_label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(310, 50, 191, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_label = QtWidgets.QLabel(self.frame)
        self.name_label.setGeometry(QtCore.QRect(60, 20, 71, 20))
        self.name_label.setObjectName("name_label")
        self.contact_name = QtWidgets.QLineEdit(self.frame)
        self.contact_name.setGeometry(QtCore.QRect(20, 40, 151, 28))
        self.contact_name.setText("")
        self.contact_name.setObjectName("contact_name")
        self.number_label = QtWidgets.QLabel(self.frame)
        self.number_label.setGeometry(QtCore.QRect(60, 80, 71, 20))
        self.number_label.setObjectName("number_label")
        self.contact_number = QtWidgets.QLineEdit(self.frame)
        self.contact_number.setGeometry(QtCore.QRect(20, 100, 151, 28))
        self.contact_number.setObjectName("contact_number")
        self.delete_button = QtWidgets.QPushButton(self.frame)
        self.delete_button.setGeometry(QtCore.QRect(50, 240, 90, 28))
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setObjectName("delete_button")
        self.add_button = QtWidgets.QPushButton(self.frame)
        self.add_button.setGeometry(QtCore.QRect(50, 200, 90, 28))
        self.add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_button.setObjectName("add_button")
        self.logs = QtWidgets.QTextBrowser(Dialog)
        self.logs.setGeometry(QtCore.QRect(20, 370, 481, 91))
        self.logs.setObjectName("logs")
        self.contacts_list = QtWidgets.QTextBrowser(Dialog)
        self.contacts_list.setGeometry(QtCore.QRect(20, 50, 281, 311))
        self.contacts_list.setObjectName("contacts_list")

        self.retranslateUi(Dialog)
        self.add_button.clicked.connect(self.AddNumber)
        self.delete_button.clicked.connect(self.DeleteNumber)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Phone Book"))
        self.contacts_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Contacts</span></p></body></html>"))
        self.name_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Name</span></p></body></html>"))
        self.contact_name.setPlaceholderText(_translate("Dialog", "Name"))
        self.number_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Number</span></p></body></html>"))
        self.contact_number.setPlaceholderText(_translate("Dialog", "Phone Number"))
        self.delete_button.setText(_translate("Dialog", "Delete"))
        self.add_button.setText(_translate("Dialog", "Add"))

    def WriteLog_Add(self):
        os.chdir(r'../log')
        logfile = 'log.txt'
        with open(logfile, 'a', encoding='utf-8') as log_file:
            log_file.write(f'[{datetime.datetime.now()}] Added a contact --> {self.contact_name.text().title()} : {self.contact_number.text()}\n')
    
    def WriteLog_Delete(self):
        os.chdir(r'../log')
        logfile = 'log.txt'
        with open(logfile, 'a', encoding='utf-8') as log_file:
            log_file.write(f'[{datetime.datetime.now()}] Deleted a contact --> {self.contact_name.text().title()} : {self.contact_number.text()}\n')
    
    def AddNumber(self):
        app.processEvents()
        os.chdir(r'../log')
        filename = 'phonebook.txt'
        with open(filename, 'a') as pb_file:
            pb_file.write(f'{self.contact_name.text().title()} : {self.contact_number.text().title()}\n')
        self.contacts_list.append(f'{self.contact_name.text().title()} : {self.contact_number.text()}')
        self.logs.append(f'{datetime.datetime.now()}')
        self.logs.append(f'Added a contact --> {self.contact_name.text().title()} : {self.contact_number.text()}')
        self.WriteLog_Add()

    def DeleteNumber(self):
        app.processEvents()
        os.chdir(r'../log')
        filename = 'phonebook.txt'
        with open(filename, 'r') as pb_file:
            numbers = pb_file.readlines()
        for n in numbers:
            if self.contact_name.text().title() in n:
                numbers.remove(n)
                with open(filename, 'w') as pb_file:
                    pb_file.write("".join(numbers))
        self.logs.append(f'{datetime.datetime.now()}')
        self.logs.append(f'Deleted a contact --> {self.contact_name.text().title()}\nChanges will apply with a restart\n')
        self.WriteLog_Delete()

    def ShowNumbers(self):
        with open('../log/phonebook.txt', 'r') as f:
            lines = f.readlines()
        for l in lines:
            self.contacts_list.append(l.replace('\n', ''))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    ui.ShowNumbers()
    sys.exit(app.exec_())
